### ISSUE TITLE
"FileNotFoundError: [WinError 2] The system cannot find the file specified" when attempting to install package

### ISSUE THREAD

**Issue by thegreatestminer** [vapoursynth/vsrepo#110]
I installed Python 3.7.6 for all users, and then I installed VapourSynth (bundled with VSRepo) into C:\VapourSynth-32. I'm not certain why it cannot find 7z.exe, considering I do have it installed, along with it being copied into PATH.

```
C:\VapourSynth-32\vsrepo>vsrepo install kagefunc
Fetching: https://github.com/EleonoreMizo/fmtconv/releases/download/r20/fmtconv-r20.zip
Traceback (most recent call last):
  File "C:\VapourSynth-32\vsrepo\vsrepo.py", line 457, in <module>
    res = install_package(name)
  File "C:\VapourSynth-32\vsrepo\vsrepo.py", line 341, in install_package
    res = install_package(dep)
  File "C:\VapourSynth-32\vsrepo\vsrepo.py", line 341, in install_package
    res = install_package(dep)
  File "C:\VapourSynth-32\vsrepo\vsrepo.py", line 344, in install_package
    res = install_files(p)
  File "C:\VapourSynth-32\vsrepo\vsrepo.py", line 318, in install_files
    result = subprocess.run([cmd7zip_path, "e", "-so", tfpath, fn_props[0]], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Python37-32\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

![Capture](https://user-images.githubusercontent.com/19188146/62822024-e88ce580-bb4b-11e9-9d06-99a7e7808e26.PNG)

I am running Windows 7 Professional x86.

**Comment by myrsloik** [comment]
I have no idea how this can fail. Does it magically work if you copy 7z.exe to the same directory as vsrepo.py?

**Comment by Hrxn** [comment]
Off the top of my head, I can think of two ways how this can fail.

- The `REG_SZ` key for the path being present does not actually mean that `7z.exe` is in the location it purports to be

- I'm not familiar with how Python`s `winreg` works (with regard to the `OpenKeyEx` and `QueryValueEx` functionalities given in the example), but if a given path contains whitespace (like this example), is that properly handled?

**Comment by thegreatestminer** [comment]
I ended up fixing it by nuking the entire chunk and just replacing it with

`cmd7zip_path = r'C:\Program Files\7-Zip\7z.exe'

And no, copying the executable into the same directory as vsrepo.py did not fix it.

**Comment by Hrxn** [comment]
Putting `7z.exe` into a directory that's actually in your `PATH` would have worked as well, I bet.

**Comment by stuxcrystal** [comment]
I'd like to remind everyone that simple string concatenation is one of the worst ways to join a path. Use `pathlib.Path.__div__` or `os.path.join` to join pathes.
