### ISSUE TITLE
vsrupdate.py can not update directly linked dlls

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#112]
Check this:

```
{
	"name": "Warpsharp",
	"type": "VSPlugin",
	"description": "Warpsharp floating point version",
	"github": "https://github.com/IFeelBloated/warpsharp",
	"doom9": "https://forum.doom9.org/showthread.php?t=176796",
	"category": "Other",
	"identifier": "com.zonked.awarpsharp2",
	"namespace": "warpsf",
	"releases": [
		{
			"version": "",
			"published": "",
			"win64": {
				"url": "https://github.com/IFeelBloated/warpsharp/releases/download/r1/warpsharpsf.dll",
				"files": {
					"warpsharpsf.dll": [
						"warpsharpsf.dll",
						"hash"
					]
				}
			}
		}
	]
}
```

**Comment by myrsloik** [comment]
Provide an error message or better description.

**Comment by theChaosCoder** [comment]
The "error" would be **No win64 binary found**. It seems vsrupdate can only handle zip/7z files.
So the result is always like this:
```
	"releases": [
		{
			"version": "r1",
			"published": "2019-08-24T10:38:33Z"
		},
		{
```

**Comment by myrsloik** [comment]
Works perfectly here. It uses the same code path as for uncompressed scripts.

**Comment by myrsloik** [comment]
Yes, this is indeed unsupported but the answer is to compress releases like a sane person in my opinion.

**Comment by theChaosCoder** [comment]
In this case it does not save that much bandwidth: 28kb dll vs 15kb zip. 
I guess that means you won't add support for it?

**Comment by myrsloik** [comment]
No, definitely won't bother. It's actually a horrible idea not to compress because then normal users (not using vsrepo to automatically check file hash) won't realize if the download is corrupt.
