### ISSUE TITLE
Skip pre-releases in vsrupdate?

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#120]
I think vsrupdate should ignore pre-releases and process only "final releases" 
Currently this would be added too: 
https://github.com/IFeelBloated/vapoursynth-mvtools-sf/releases/tag/r10_pre

It can be checked with `"prerelease": true,`
https://api.github.com/repos/IFeelBloated/vapoursynth-mvtools-sf/releases

**Comment by myrsloik** [comment]
Makes sense

**Comment by myrsloik** [comment]
Done
