### ISSUE TITLE
A very simple question about the usage of vsrepo.py

### ISSUE THREAD

**Issue by Jiang-yan-wei** [vapoursynth/vsrepo#126]
I installed vapoursynth and I want to install some plugins by vsrepo.py.
But It can't work by the command in doc.
Such as
![image](https://user-images.githubusercontent.com/50770474/86928943-d2c2de80-c167-11ea-907f-fcca1ac80bdb.png)
Is anything wrong? Or I made a stupid mistake?

**Comment by myrsloik** [comment]
`vsrepo install havsfunc`

**Comment by theChaosCoder** [comment]
You have a typo. It must be ava**il**able and not ava**li**able

**Comment by Jiang-yan-wei** [comment]
> You have a typo. It must be ava**il**able and not ava**li**able

I feel sorry for this typo, but the problem still remains. I open cmd in `D:\VapourSynth\vsrepo`: 
![image](https://user-images.githubusercontent.com/50770474/86986093-64ad0480-c1c5-11ea-9684-c76316fb118d.png)
And I can do nothing through vsrepo.py......
![image](https://user-images.githubusercontent.com/50770474/86986184-a473ec00-c1c5-11ea-8ad3-ea252553767e.png)

Maybe the environment variables are not right? I will try to reinstall Vapoursynth now, if it still not works, I will try it in Ubuntu of our university.
Thanks for your help!

**Comment by Jiang-yan-wei** [comment]
> `vsrepo install havsfunc`

vsrepo is not a commander or .exe or .bat,...
I will reinstall Vapoursynth, thanks for your help.

**Comment by Jiang-yan-wei** [comment]
> `vsrepo install havsfunc`

It still refuse to work...
I reinstalled vapoursynth and python3.8, I believe there are no errors in environment.
I open cmd in `.\VapourSynth\vsrepo` and input: `vsrepo install ffms2` 
![image](https://user-images.githubusercontent.com/50770474/87001795-d77ca680-c1ea-11ea-8393-a6d4c4bdb291.png)
Then I tried many possible commands:
`vsrepo.py install ffms2`
`vsrepo available`
But it always report this:
![image](https://user-images.githubusercontent.com/50770474/87001896-21fe2300-c1eb-11ea-8ea3-5e1996054224.png)
I open `vsrepo.py` in VSCODE, tried to install by my hands through the method in `vsrepo.py`. But I failed to do it. Noob me .
Can you help me find this problem? I'm going to be crazy..... Many thanks...

**Comment by Jiang-yan-wei** [comment]
> `vsrepo install havsfunc`

I have solved this problem.... really stupid, thank you!
