### ISSUE TITLE
preserve original timestamps

### ISSUE THREAD

**Issue by stax76** [vapoursynth/vsrepo#129]
vsrepo could possibly be used to update vapoursynth plugins in staxrip, but without original timestamps, I don't know.

In staxrip the tools dialog shows the timestamps and I find this to be **incredibly useful information**.

![Untitled](https://user-images.githubusercontent.com/11410540/89705110-b67ab300-d95a-11ea-8a18-fa3c97d8a2e1.png)

This dialog is packed with useful features, pressing the version button for avisynth:

![noversion](https://user-images.githubusercontent.com/11410540/89705211-b7f8ab00-d95b-11ea-9fb7-da99140058fc.png)

vapoursynth does not have file resource version info, OK it's missing more often than not for any tool.

**Comment by theChaosCoder** [comment]
As far as I understand vsrepo "extracts" to stdout and checks if the hash matches (this method avoids a tmp file). Maybe after checking for a valid hash a second "normal" 7z-extract command can be executed (we know that the file hash matches).

**Comment by myrsloik** [comment]
Why do you need timestamps if you have detailed version information from a much more reliable hash? This makes no sense at all.

**Comment by stax76** [comment]
I would like to know when something was built and released, the last write date gives a clue about that, it's something I expect from any package management tool.

**Comment by myrsloik** [comment]
I'd rather add a release timestamp to the vsrepo output then...
