### ISSUE TITLE
fetch_url_to_cache not reliable

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#130]
urlreq.info().get_filename() in fetch_url_to_cache() does not work with every link. In "avsrepo" is solved it by using basename(url) instead of get_filename() but maybe there is a better "more corect" way to do it.

Check here with url: https://files.pythonhosted.org/packages/73/c8/6dd6f80356131fe2f8b0da4499dcc2ee26d2207e95389d409c5c61b5bd32/vsutil-0.5.0-py3-none-any.whl
dlfile = fetch_url_to_cache(url, "package", "creator", "")

```
line 114, in fetch_url_to_cache
    cache_path = 'dlcache/' + name + '_' + tag_name + '/' + urlreq.info().get_filename()
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by myrsloik** [comment]
That's probably the correct solution. With urlreq.info().get_filename() you'd instead get the filename from the headers which the remote server will report as something different sometimes and then everything derps out. Go ahead and apply it.
