### ISSUE TITLE
Wheel package + old dist info = upgrade loop

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#132]
I just updated the **pvsfunc** wheel package, but vsrepo still shows that the old version is installed. (update was successfull)

```
vsrepo upgrade-all
Rebuilding dist-info dirs for other python package installers
pvsfunc 3.6.3: 100%|██████████████████████████████████████████████████████████████| 26.3k/26.3k [00:00<00:00, 3.06MB/s]
Successfully installed pvsfunc 3.6.3
Updating VapourSynth stubs
1 package upgraded
```
(It will install the same package everytime I run vsrepo upgrade-all )

I noticed in `AppData\Roaming\Python\Python38\site-packages` there are 2 dist info folders:

- pvsfunc-3.5.1.dist-info
- pvsfunc-3.6.3.dist-info

Removing manually the pvsfunc-3.5.1.dist-info folder seems to fix the problem.

**Comment by myrsloik** [comment]
Probably mostly fixed.
