### ISSUE TITLE
Where can I find 'vspackages3.json'?

### ISSUE THREAD

**Issue by markfilipak-windows** [vapoursynth/vsrepo#133]
Where can I find 'vspackages3.json'? When I get it, where do I put it in a portable installation?

C:\CMD & tiny apps\VapourSynth>python vsrepo.py available
Failed to open vspackages3.json. Run update command.

C:\CMD & tiny apps\VapourSynth>update
'update' is not recognized as an internal or external command,
operable program or batch file.

C:\CMD & tiny apps\VapourSynth>dir /s *update*.*
 Volume in drive C is \Device\Harddisk0\DR0
 Volume Serial Number is D8AD-00FF
File Not Found

**Comment by markfilipak-windows** [comment]
In that 3rd command, the line is "dir /s STARupdateSTAR.STAR

**Comment by markfilipak-windows** [comment]
Originally Posted by lansing View Post
the command is
Code:

python vsrepo.py update

Thank you. I ran it and got this:

Code:

C:\CMD & tiny apps\VapourSynth>python vsrepo.py update
Traceback (most recent call last):
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "http\client.py", line 921, in connect
  File "socket.py", line 808, in create_connection
  File "socket.py", line 796, in create_connection
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vsrepo.py", line 909, in <module>
    update_package_definition('http://www.vapoursynth.com/vsrepo/vspackages3.zip')
  File "vsrepo.py", line 713, in update_package_definition
    with urllib.request.urlopen(req_obj) as urlreq:
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1379, in http_open
  File "urllib\request.py", line 1353, in do_open
urllib.error.URLError: <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>

Clue: 'http://www.vapoursynth.com/vsrepo/vspackages3.zip'

I download that. Inside was 'vspackages3.json'. Hurrah! Now, where do I put it?

**Comment by markfilipak-windows** [comment]
Never mind. After putting copies everywhere and failing, I put a copy here:
c:\Users\Administrator\AppData\Roaming\VapourSynth\vsrepo\
and 'python vsrepo.py available' then succeeded.

This project makes too many assumptions and supplies too little documentation (e.g. typical installation) and too little communication.

**Comment by markfilipak-windows** [comment]
After much experimentation, I put svpflow1 & svpflow2 here:
c:\Users\Administrator\AppData\Roaming\VapourSynth\plugins64\svpflow1.dll
c:\Users\Administrator\AppData\Roaming\VapourSynth\plugins64\svpflow2.dll
then reran
python vsrepo.py available.
The resulting plugin list did not include either svpflow.
Why?

**Comment by DJATOM** [comment]
Всё просто: портабл версия использует плагины с вложенной папки, а не с пользовательской директории программ. Чтобы vapoursynth увидел плагин, он должен находиться в (папка с портабл vapoursynth)\vapoursynth64\plugins. Вполне логично использовать вложенную директорию для портабл версии, а не зависеть от глобальной.

**Comment by markfilipak-windows** [comment]
DJATOM wrote:
"It's simple: the portable version uses plugins from a subfolder, not from the user's program directory. For vapoursynth to see the plugin, it must be located in (vapoursynth portabl folder) \ vapoursynth64 \ plugins. It is quite logical to use a nested directory for the portable version, and not depend on the global one."

It's not simple. It's a disaster.

C:\CMD & tiny apps\VapourSynth>python vsrepo.py installed
Name                      Namespace       Installed   Latest      Identifier

C:\CMD & tiny apps\VapourSynth>

So nothing is installed? What a mess.

**Comment by markfilipak-windows** [comment]
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\avisource.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\AvsCompat.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\EEDI3.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\libhistogram.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\libimwri.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\libsubtext.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\MiscFilters.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\Morpho.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\RemoveGrainVS.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\Vinverse.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\coreplugins\VIVTC.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\plugins\.keep
c:\CMD & tiny apps\VapourSynth\vapoursynth64\plugins\svpflow1.dll
c:\CMD & tiny apps\VapourSynth\vapoursynth64\plugins\svpflow2.dll
