### ISSUE TITLE
lvsfunc old versions

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vsrepo#137]
vsrepo currently only stores the old single python script for lvsfunc, which breaks setups and scripts relying on a more up-to-date version and continually brings me headaches when users ask me about it. lvsfunc has since been updated to a [proper Python package](https://github.com/Irrational-Encoding-Wizardry/lvsfunc), and is also available on [PyPi](https://pypi.org/project/lvsfunc/). I'm not entirely sure how to update it for a PR, so I figured I'd at least leave an Issue.

**Comment by LightArrowsEXE** [comment]
The issue with the old py file is both that it seems to take precedence when trying to import modules and that it's very outdated, causing users to ask me why certain functions are missing or why lvsfunc "won't work" (because it's trying to load the old .py) quite frequently.

**Comment by theChaosCoder** [comment]
And I also have the same problem in vsrepo with lvsfunc now. vsrepo thinks an older version is still installed. See https://github.com/vapoursynth/vsrepo/issues/132

Remove the dist-info folder (and maybe lvsfunc) and re-install. But the problem can appear in the next update.

**Comment by theChaosCoder** [comment]
The new lvsfunc package is now uploaded too. The old one needs to be removed manually.

**Comment by myrsloik** [comment]
The type change causes vsrepo to not realize it also has to manually remove the dist-info (which will be done as a part of the normal package uninstall process when it's a PyWheel type). Mixing package types isn't allowed so this is more or less a horrible corner case.
