### ISSUE TITLE
VideoNode.output type hint

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vsrepo#140]
The documentation says we can use a function of the form `func(current_frame, total_frames)` to to *progress_update*.

https://github.com/vapoursynth/vsrepo/blob/49a39b4ec03cc44101c3b83932e44db266d68014/vsgenstubs/_vapoursynth.part.pyi#L382

Shouldn't typing be something like that:
```py
progress_update: typing.Optional[typing.Callable[[int, int]]]=None
```

**Comment by myrsloik** [comment]
Definitely look wrong, will take a look

**Comment by myrsloik** [comment]
Probably fixed now
