### ISSUE TITLE
AttributeError: module 'vapoursynth' has no attribute 'Format'

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vsrepo#155]
The stubs are outdated and they provide false informations about the current headers in R55 APIv4

**Comment by myrsloik** [comment]
I've started updating things in the genstubs4 dir if you want to help. I think I fixed some of the most important problems but more annotations are definitely needed for all new classes like AudioNode and AudioFrame.
It also needs start using the return_signature.

**Comment by Ichunjo** [comment]
I don’t see any `genstubs4` dir right now in the master branch. Or do you mean you started in a local branch?

**Comment by myrsloik** [comment]
Forgot to push
