### ISSUE TITLE
stubs are broken

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vsrepo#156]
A message at the beginning of the file is showed:

```py
C:\Program Files\VapourSynth\vsrepo\vsgenstubs\__init__.py:51: DeprecationWarning: get_plugins() is deprecated. Use "plugins()" instead.
  for v in core.get_plugins().values():
# Stop pep8 from complaining (hopefully)
# NOQA
```

Most of the return types returns just `Any` or `typing.Optional[Any]`
```py
class _Plugin_ffms2_Unbound(Plugin):
    """
    This class implements the module definitions for the corresponding VapourSynth plugin.
    This class cannot be imported.
    """
    def GetLogLevel(self) -> typing.Optional[Any]: ...
```
Here’s the stubs I currently have [__init__.zip](https://github.com/vapoursynth/vsrepo/files/7199322/__init__.zip)

**Comment by Ichunjo** [comment]
The `typing.Optional[Any]` seems to be the APIv4 module

**Comment by myrsloik** [comment]
Right, _vapoursynth.part.pyi and the generation bit needs to be updated for R55. Should also keep the old version aroud so we're compatible with both branches.
