### ISSUE TITLE
Generate dist info for linux

### ISSUE THREAD

**Issue by YomikoR** [vapoursynth/vsrepo#159]
This is a part of vsrepo.py which refuses to work for non Windows systems.

**Comment by myrsloik** [comment]
It was only designed to work on windows. Figure out how to detect the correct paths for everything on linux/osx and I guess I can make a minimal effort to support it.

**Comment by YomikoR** [comment]
For your reference, vsgenstubs4 is placing the stubs folder in correct places.

**Comment by YomikoR** [comment]
Would you like to first implement the dist info for VS? This might effectively prevent users pip installing the wrong thing.
