### ISSUE TITLE
vsutil 0.6.0

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vsrepo#168]
vsutil has been updated and 0.6.0 has been available on pypi for a while now.

https://pypi.org/project/vsutil/0.6.0/

**Comment by theChaosCoder** [comment]
For some reason the updater does not see the new version...

**Comment by stuxcrystal** [comment]
I think I know what is going on:

I did not upload a wheel for that project in 0.6.0.

Maybe we should also add .tar.gz-files and make pip install the
dependency instead.

**Comment by myrsloik** [comment]
What's the difference between a .tar.gz and a wheel for this?

**Comment by stuxcrystal** [comment]
Just take one of the artifacts (prefer bdist_wheel) and run

    pip install [FILE] --no-deps

That would be all.

I prefer you omit --no-deps tho since pip will then also install
dependencies outside of vsrepo, like numpy or similar.

**Comment by LightArrowsEXE** [comment]
Will this see any movement anytime soon? Got another person who had an outdated vsutil today because of vsrepo.

**Comment by myrsloik** [comment]
Patches welcome. Otherwise maybe not? I have gotten myself a REAL LIFE

**Comment by theChaosCoder** [comment]
I see 2 quick fixes for this. 1) just upload a wheel file again. 2) vsrepo treats it as a "regural" pyscript and not as a wheel file. 
Since we have a "create package" helper function now, managing multiple files is not an annoying problem anymore which had to be done by hand before.

There should be no problem if the vsutil folder is just copied into the scripts folder, correct? This is what pip or wheel basically do?

**Comment by theChaosCoder** [comment]
So I guess we should delete the vsutil package for now until a solution is found. This way people don't get confused why some scripts aren't working properly. 
Any other suggestions?

**Comment by myrsloik** [comment]
Delete it

**Comment by Setsugennoao** [comment]
vsutil is now at version 0.8.0 and is stable, shouldn't this get resolved?

**Comment by theChaosCoder** [comment]
If .whl files will be provided it can be added again. This was the whole issue with v0.6 => no .whl file

**Comment by nobananasforyou** [comment]
> The wheel file is available on PyPi https://pypi.org/project/vsutil/#files

Latest release of vsutil is 0.7.0 https://github.com/Irrational-Encoding-Wizardry/vsutil/releases so why is the .whl file tagged as vsutil-0.8.0.tar.gz?

**Comment by theChaosCoder** [comment]
Added back again
