### ISSUE TITLE
adding bas

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vsrepo#170]
Chaos, can you add [BestAudioSource](https://github.com/vapoursynth/bestaudiosource) please

**Comment by theChaosCoder** [comment]
No, because it is already added :D 
https://github.com/vapoursynth/vsrepo/blob/master/local/bas.json

**Comment by Ichunjo** [comment]
Oh! Should it be on vsdb too then?

**Comment by theChaosCoder** [comment]
It's all done by hand currently. 
Locally I have a much better version in development which automates some stuff (second rewrite xD). 
But it's on veeeery low priority + I'm very lazy :P

**Comment by Ichunjo** [comment]
> But it's on veeeery low priority + I'm very lazy :P

Understandable. 

Thank you!
