### ISSUE TITLE
vsrepo.py = Could not detect vapoursynth

### ISSUE THREAD

**Issue by M70000** [vapoursynth/vsrepo#173]
When i put something like `vsrepo.py update` in cmd or `vsrepo.py install` in cmd i receive this error
`Could not detect vapoursynth` i have no idea of how to fix, someone please help, my vapoursynth is installed correctly.

**Comment by theChaosCoder** [comment]
I have the same problem since around the R57 release. 
```

def detect_vapoursynth_installation():
    for loader in sys.meta_path:
        if loader.find_module("vapoursynth") is not None:
            break
    else:
        print("Could not detect vapoursynth")
        sys.exit(1)

```
Idk what happend or was changed in python but **loader.find_module("vapoursynth")** is always None. I also reinstalled R57 but same result. I'm using Python3.9.
```

**Comment by theChaosCoder** [comment]
According to https://stackoverflow.com/a/37260391/8444552  find_module is deprecated
this seems to work importlib.util.find_spec('vapoursynth')
