### ISSUE TITLE
some deprecated links

### ISSUE THREAD

**Issue by hooke007** [vapoursynth/vsrepo#182]
https://github.com/vapoursynth/vs-miscfilters-obsolete
https://github.com/vapoursynth/vs-removegrain
... and more

Such repos now use independent ones.

**Comment by theChaosCoder** [comment]
They are in the repo...
https://github.com/vapoursynth/vsrepo/blob/master/local/misc.json
https://github.com/vapoursynth/vsrepo/blob/master/local/rgvs.json

What's your suggestion? Remove them? 
Where can i find the independent ones?

**Comment by hooke007** [comment]
Sry it seems I posted in the wrong issue tracker.
https://github.com/theChaosCoder/vsdb/issues

I.e.
https://vsdb.top/plugins/rgvs links to https://github.com/vapoursynth/vapoursynth rather than https://github.com/vapoursynth/vs-removegrain

**Comment by theChaosCoder** [comment]
Ah I see, not really a vsrepo issue but links are corrected now 😊
