### ISSUE TITLE
vs-placebo v1.4.2 missing additional dependency

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vsrepo#183]
Starting with v1.4.2, vs-placebo requires libdovi on Windows (as per https://github.com/Lypheo/vs-placebo/issues/27), or VapourSynth will simply not recognise it. `vsrepo` [does not package this file currently](https://github.com/vapoursynth/vsrepo/blob/master/local/placebo.json#L15-L19=), making it very easy to run into this issue without an immediate solution.

**Comment by theChaosCoder** [comment]
Same applies to most cuda/gpu packages...
I added the lib, please test the installation.
