### ISSUE TITLE
Add new packages

### ISSUE THREAD

**Issue by Setsugennoao** [vapoursynth/vsrepo#185]
Hello! I recently created some new packages, could you add them to vsrepo? They also are all on PyPi.

- [vs-exprtools](https://github.com/Irrational-Encoding-Wizardry/vs-exprtools), [whl](https://files.pythonhosted.org/packages/12/8b/1698191f58b5999eaf4c9187f69580346ac19dc3ab5c0da58aa6e0c6e911/vsexprtools-1.0.1-py3-none-any.whl)
- [vs-rgtools](https://github.com/Irrational-Encoding-Wizardry/vs-rgtools), [whl](https://files.pythonhosted.org/packages/0f/24/86de58d6692a8ef627404596b1fb3b2b8e5fb3c4fcba3b474d2deb900b73/vsrgtools-0.1.10-py3-none-any.whl)
- [vs-kernels](https://github.com/Irrational-Encoding-Wizardry/vs-kernels), [whl](https://files.pythonhosted.org/packages/bc/c4/cb7abb33e9298b3ae5519e553538592ed6999bc8cd2d98b18454063890c0/vskernels-1.1.3-py3-none-any.whl), (with @LightArrowsExe)
- [vs-aa](https://github.com/Irrational-Encoding-Wizardry/vs-aa), [whl](https://files.pythonhosted.org/packages/ef/60/0862fe089b53d754584d2c5cd2daa0fca97d344cfe46bb13c90b7ac6b488/vsaa-1.0.1-py3-none-any.whl)
- [vs-dehalo](https://github.com/Irrational-Encoding-Wizardry/vs-dehalo), [whl](https://files.pythonhosted.org/packages/5a/a5/79a6330c32bbd49a4b1bf8474176d754d7e557fb9572d931171603e68f72/vsdehalo-0.1.5-py3-none-any.whl)
- [vs-scale](https://github.com/Irrational-Encoding-Wizardry/vs-scale), [whl](https://files.pythonhosted.org/packages/f2/46/3b2ce6f7e30d9eeabf0ce28e072e6a2c582fddcaf3713aa89cdb6f698da9/vsscale-0.1.0-py3-none-any.whl)
- [vs-dfft](https://github.com/Irrational-Encoding-Wizardry/vs-dfft), [whl](https://files.pythonhosted.org/packages/33/9d/471682b0ecab628e8ab0e069087239de94183481d67c00fe50481d37f0e3/vsdfft-0.1.0-py3-none-any.whl)
- [vs-parsedvd](https://github.com/Irrational-Encoding-Wizardry/vs-parsedvd), [whl](https://files.pythonhosted.org/packages/22/78/d770cfd645a74134c5acb333ac7dd241c114149c46a721adbfe879e28a5a/vsparsedvd-0.0.4-py3-none-any.whl)
- [vs-preview](https://github.com/Irrational-Encoding-Wizardry/vs-preview), [whl](https://files.pythonhosted.org/packages/7c/1b/beb3dbfa98aaf148ff0f25bfbc976343437b6243b124b2b2907c683adcfe/vspreview-0.2.7-py3-none-any.whl), (mod of the now unmaintained [vapoursynth-preview](https://github.com/Endilll/vapoursynth-preview))
- [stgfunc](https://github.com/Setsugennoao/stgfunc), [whl](https://files.pythonhosted.org/packages/8e/49/081ffc19f167d22a2a443670d2463475376dd2f3635614c3f304266fdc9c/stgfunc-1.0.0-py3-none-any.whl)

@theChaosCoder It would also be cool to have you in the [IEW Discord server](https://discord.gg/cGPrke9pw3), if you use Discord. Thanks!

**Comment by theChaosCoder** [comment]
Will add them soon. 
Only vs-preview feels wrong to add, it's not really a plugin/script.

**Comment by Setsugennoao** [comment]
Mhhkay, fair.

**Comment by theChaosCoder** [comment]
Hmm one problem however is that some packages have additional dependencies like parsedvd which installs pyparsedvd if you use pip.

**Comment by theChaosCoder** [comment]
Possible solutions:
- Wheel packages with "external" dependencies will be dropped (bye bye lvsfunc 😅)
- A message will be shown: "Additional dependencies are required, please run pip install xyz OR check readme of package xy for further steps"
- Some programms a addMissingDeps() function to vsrepo

**Comment by theChaosCoder** [comment]
Some packages are removed until a solution is found for the missing dependencies. It does not make sense to offer these if they won't work after installing them but would work via pip. 
So just use pip for now.
