### ISSUE TITLE
fftw3 3.3.10 update request.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vsrepo#188]
fftw3 already updated to 3.3.10.

But the repository only has old 3.3.5 editions.

So I build the 3.3.10 follow by filler56789's post: https://forum.doom9.org/showthread.php?t=174470&page=6

MSVC build by vcpkg with Visual Studio 2022 v17.3.4.

```
vcpkg install fftw3[sse2,avx,avx2,threads]:x64-windows
vcpkg install fftw3[sse2,avx,avx2,threads]:x86-windows
```

GCC 12.2 build by msys2 with all editions (mingw32/mingw64/ucrt64) 

build config:

```
libfftw3-3.dll
./configure --enable-shared --enable-sse2 --enable-avx --enable-avx2 --disable-fortran --enable-threads --with-combined-threads --with-our-malloc

libfftw3f-3.dll
./configure --enable-shared --enable-float --enable-sse2 --enable-avx --enable-avx2 --disable-fortran --enable-threads --with-combined-threads --with-our-malloc

libfftw3l-3.dll
./configure --enable-shared --enable-long-double --disable-fortran --enable-threads --with-combined-threads --with-our-malloc
```

download:

[FFTW-3.3.10.zip](https://github.com/vapoursynth/vsrepo/files/9612142/FFTW-3.3.10.zip)

**Comment by myrsloik** [comment]
We definitely should update the binaries some day. Which version is faster? mingw?
It's also annoying if we have to host things ourselves. Nobody builds these and uploads as github releases?

**Comment by theChaosCoder** [comment]
I just updated fftw3 (mingw binaries, not tested for best speed). Should we include libfftw3l-3.dll?

**Comment by fuchanghao** [comment]
> We definitely should update the binaries some day. Which version is faster? mingw? It's also annoying if we have to host things ourselves. Nobody builds these and uploads as github releases?

I prefer MinGW build because MSVC build is not recommended for official sources. (official cmake files and sources need to be patched to build by MSBuild).

**Comment by fuchanghao** [comment]
> I just updated fftw3 (mingw binaries, not tested for best speed). Should we include libfftw3l-3.dll?

I don't know if is needed by some vapoursynth plugins, I just see old FFTW 3.3.5 Windows DLLs have  libfftw3l-3.dll so I also build it.

**Comment by myrsloik** [comment]
Nothing uses long double. Ever.
