### ISSUE TITLE
[Update Request] VapourSynth-ICCConvert 4.1

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vsrepo#191]
https://github.com/YomikoR/VapourSynth-ICCConvert/releases/tag/4.1

**Comment by theChaosCoder** [comment]
Updated 6 days ago
https://github.com/vapoursynth/vsrepo/blob/6e2d2c97760525c92aa0498fbfa96795c3020720/local/iccc.json#L24

**Comment by fuchanghao** [comment]
> Updated 6 days ago
> 
> https://github.com/vapoursynth/vsrepo/blob/6e2d2c97760525c92aa0498fbfa96795c3020720/local/iccc.json#L24

But Is still says the 4.0 version on VSRepoGUI

Even I put the 4.1 files on plugin folder

It still says unknown.

![屏幕截图 2022-11-26 221917](https://user-images.githubusercontent.com/11471475/204093424-231a652d-bd44-4061-b9d3-6e0e1a21e8a6.png)

**Comment by theChaosCoder** [comment]
Someone forgot to upload the packages zip 😇
Please check again.

**Comment by fuchanghao** [comment]
thanks works now.
