### ISSUE TITLE
vsgenstubs stores exception

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vsrepo#196]
When generating or updating the VS stubs, the following exception occurs...

```py
Traceback (most recent call last):
  File "C:\Users\light\AppData\Local\Programs\Python\Python310\lib\site-packages\vsgenstubs4\__init__.py", line 1, in <module>
    from .init import main  # noqa: F401
ImportError: attempted relative import with no known parent package
```

...except it stores this inside the `__init__.pyi` file

![image](https://user-images.githubusercontent.com/42927908/209890104-b1783872-f201-4d4c-a0d4-af4bd6f4ab76.png)

This means stubs never load, however running `vsgenstubs4` myself from the terminal seems to properly stick them in the local `site-packages`. However, the roaming one gets prioritised, meaning stubs never get loaded. plsfix.

**Comment by Setsugennoao** [comment]
Imo vsrepo shouldn't even handle any output path and the sort, just blindly open subprocess of vsgenstubs4 and that's it
Doesn't even make sense to have one in roaming site-packages and another in the actual install

**Comment by Setsugennoao** [comment]
This is fixed upstream now.

**Comment by LightArrowsEXE** [comment]
This still seems to persist when using `vsrepo install plugin`. I can fix it manually by deleting the `vapoursynth-stubs/__init__.pyi` file and running `vsgenstubs4` after, but that's rather annoying.
