### ISSUE TITLE
(Portable) vsrepo install   , The installation directory is not in VapourSynth64-Portable-R61\Lib\site-packages

### ISSUE THREAD

**Issue by rr4e** [vapoursynth/vsrepo#205]
Why does vsrepo install install the script in the VapourSynth64-Portable-R61 root directory instead of VapourSynth64-Portable-R61\Lib\site-packages

<img width="347" alt="QQ截图20230330174153" src="https://user-images.githubusercontent.com/14058293/228797101-5feb26c3-013e-4b41-a140-0d41d4370f2a.png">

**Comment by theChaosCoder** [comment]
It was always like this. A portable env is not really defined. You need to specify a -s SCRIPT_PATH
