### ISSUE TITLE
BestSource support

### ISSUE THREAD

**Issue by Ironclad17** [vapoursynth/vsrepo#213]
It seems like an essential feature for any of the audio editing but I can't find a compiled .dll anywhere on the repo.
https://github.com/vapoursynth/bestsource

This was the latest release I could find which is clearly behind.
https://forum.doom9.org/showthread.php?t=184255

**Comment by theChaosCoder** [comment]
Done https://github.com/vapoursynth/vsrepo/commit/5db06f9124edbed55a0bb369fe1a81ba0be703e9
