### ISSUE TITLE
access_token necessary?

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#26]
An access_token is not needed to query releases via the github api, why force it?

https://github.com/vapoursynth/vsrepo/blob/22bc328ef638a37dc041afd1e64e1784fc83dfa0/vsrupdate.py#L63

This works too https://api.github.com/repos/HomeOfVapourSynthEvolution/VapourSynth-DFTTest/releases

**Comment by myrsloik** [comment]
You're only allowed to make 50 or so requests/hour/ip without a token. It will error out with 403 forbidden before everything has been queried.

**Comment by theChaosCoder** [comment]
ah ok, didn't know that.
