### ISSUE TITLE
Portable mode installs some plugins into subfolder

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#53]
`vsrepo.py -p install grain -b asd`
This works like it should, addgrain.dll is in **asd** folder

`vsrepo.py -p install w2xc -b asd`
w2xc.dll & Waifu2x-w2xc.dll end up in **asd/Win64** folder

**Comment by theChaosCoder** [comment]
Actually this is also true for the non portable mode

**Comment by myrsloik** [comment]
Doh, I grab the wrong part to base the path off. Will fix in a minute

**Comment by myrsloik** [comment]
Figured out why. I grabbed the wrong filename in the vsrupdate script when adding new entries.
