### ISSUE TITLE
Rar support?

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#64]
There is one plugin in rar archive http://rationalqm.us/hdr/

**Comment by myrsloik** [comment]
If 7zip supports decompressing it simply make a package definition and I'll add the remaining needed code.

**Comment by myrsloik** [comment]
I've recommended about 20 different things already, including 7z archives, but nobody cares. This is what happens when you try to staple a package system to an existing reality. Recommendation: pain.
