### ISSUE TITLE
traceback: hash issue with hnwvsfunc.py

### ISSUE THREAD

**Issue by hydra3333** [vapoursynth/vsrepo#68]
Hello.  It seems like a minor issue has arisen:

```
.\python.exe .\vsrepo.py -p -t win64 -f -b vapoursynth64\plugins\dll-to-choose-from -s vapoursynth64\scripts upgrade-all
Fetching: https://api.github.com/repos/Helenerineium/hnwvsfunc/zipball/v1.31
Traceback (most recent call last):
  File ".\vsrepo.py", line 455, in <module>
    inst = upgrade_all_packages(args.force)
  File ".\vsrepo.py", line 368, in upgrade_all_packages
    res = upgrade_files(get_package_from_id(id, True))
  File ".\vsrepo.py", line 346, in upgrade_files
    install_files(p)
  File ".\vsrepo.py", line 314, in install_files
    raise Exception('Hash mismatch for ' + install_fn + ' got ' + hash_result[1] + ' but expected ' + hash_result[2])
Exception: Hash mismatch for hnwvsfunc.py got e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but expected e907b1ccdd404082b4ce5235f75bba4583c83d5442cccb11cb2192616f2b0483
```

**Comment by myrsloik** [comment]
He made two releases with the same name. Therefore the new one wasn't detected. At this rate I'll probably just blacklist hnwvsfunc and remove it since the author does everything possible to break my system. The hnwvsfunc author is broken, fix him.

**Comment by hydra3333** [comment]
OK thank you.  I'll head on over there now.

**Comment by hydra3333** [comment]
OK, unless I am missing something - at https://github.com/Helenerineium/hnwvsfunc/releases shows 2 releases with different titles and tags.

I suppose an older release must have been deleted, it now only shows 2 releases unless the names/tags were edited recently.

If I knew what to look for I'd post an issue over there, however apologies I don't know what to do.

Thank you anyway, for your fantastic work !

**Comment by theChaosCoder** [comment]
I thought github does not allow 2 tags with the same name?

**Comment by theChaosCoder** [comment]
I noticed 2 things
- After this hash mismatch the scripts gets deleted, so I'm left with "nothing". Which is not nice.
- Why is this url downloaded https://api.github.com/repos/Helenerineium/hnwvsfunc/zipball/v1.31 ? The  json package on github shows only 1.24...!?

**Comment by myrsloik** [comment]
There used to be a different 1.31. Actually there was a 1.31 release that got deleted and then another 1.31 took its place. I checked against the downloaded file archive used to generate the original hash. Basically the author deletes all old releases and does everything possible to ruin my system. I'm about to simply remove hnwvsfunc because I don't have the time to deal with it. I didn't bother to commit the local changes and that's why you don't see them.

Your point about failed upgrades deleting the current package will be fixed.

**Comment by hydra3333** [comment]
Over at the hnwvsfunc github place, the author of hnwvsfunc very kindly indicated assent to a suggestion of version releases consistent with the needs of vsrepo.

Maybe there is no longer a need to do any work around removing hnwvsfunc ?

Thank you !
