### ISSUE TITLE
Bug or user fail?

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#74]
vsrepo says my hash is wrong.
But the 047.. hash is correct! I think vsrepo would be confused because the file name has a .model at the end? 

`Exception: Hash mismatch for model/model_V8a.model got 
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but expected 047ff7bfd0b51bdd51c35a6623bebe07c7b925a537ca219c8efd2be80370d683`

Also `.\vsrupdate.py -p vmaf_models  update-local` don't really work if I change my version to something else. Had to generate the hashes with my own script.

**package:** 
[vmaf_models.zip](https://github.com/vapoursynth/vsrepo/files/2557330/vmaf_models.zip)

**Comment by myrsloik** [comment]
Definitely a bug. That's the hash of null input so something didn't work properly...

**Comment by theChaosCoder** [comment]
It was a user fail after all... I forgot to add the parent folder :-/
