### ISSUE TITLE
Any simple way to install all packages?

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vsrepo#84]
There's no command like install-all.

When I list all package's namespace in one line it shows error.

`python.exe vsrepo.py install acrop adjust astdr avsw bezier bifrost bilateral bilateralgpu bm3d cnr2 colorbars colorfade ctfm d2v damb dctf deblock decross dedot delogo descale  dfmderainbow dfttest dghdrtosdr dgm DGMVC  dpid edgefixer edi_rpow2 eedi2 eedi3m fb ffms2 fft3dfilter fftw3_library fh flux fmtc focus2 ftf fvsfunc grain havsfunc hnwvsfunc hqdn3d it kagefunc knlm lostfunc mcdenoise minideen motionmask mpls msmoosh muvsfunc mv mvmulti mvsf mvsfunc nnedi3 nnedi3cl nnedi3_resample nnedi3_rpow2 nnedi3_weights noisegen oyster plum pp7 qr rainbowsmooth resamplehq retinex rgsf sangnom smoothuv ssiq tcanny tcm tcomb tdm timecube tla tmc tmedian tnlm tonemap trans ttmpsm vcfreq vcmod vcmove vd vfrtocfr vine vmaf vmaf_models vsf vsfm vstaambk w2xc w2xc_models w3fdif warp wss xvs yadifmod znedi3`

**Comment by theChaosCoder** [comment]
What is the error message?

You could install the "big" scripts first. This way most of the plugins will be installed automatically since they are an dependency. 

Try to install these first: havsfunc hnwvsfunc muvsfunc
