### ISSUE TITLE
Add dist-info directories according to PEP376 for scripts.

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vsrepo#93]
This makes sure that vsrepo interoperates with any python package management that might theoretically come preinstalled with python.

For example, pip on windows or apt or yum.

https://www.python.org/dev/peps/pep-0376/

**Comment by myrsloik** [comment]
Patches welcome

**Comment by myrsloik** [comment]
Maybe it'd be better to simply create a package and install it that way too. That wouldn't be much harder than creating all the other metadata files, right?

**Comment by stuxcrystal** [comment]
It wouldn't.

Here's an example of a setup.py that is generated from the vsrepo repository. https://warehouse.encode.moe/simple/adjust/v1.py

It only works for windows though.
You can download setup.py for other projects with on my page https://warehouse.encode.moe/

**Comment by myrsloik** [comment]
Why didn't you mention this interesting creation? It at least deserves to be linked to somewhere.

I have now made it my mission to install scripts by creating packages for them (plugins become very iffy outside of vapoursynth-portable land). Do you mind if I shamelessly borrow a few lines of the code?

**Comment by stuxcrystal** [comment]
I have given you an invite to the repository.
Please also look at the version sanitizer as vsrepo packages do not always follow the rules specified in PEP440.

**Comment by myrsloik** [comment]
Dist-info dirs are already automatically created and wheels are now the preferred method for python stuff so I guess it's done
